package models

import (
	"time"

	"github.com/google/uuid"
)

type EarningType string

const (
	EarningTypeShiftPay   EarningType = "SHIFT_PAY"
	EarningTypeCommission EarningType = "COMMISSION"
	EarningTypeBonus      EarningType = "BONUS"
	EarningTypeAdjustment EarningType = "ADJUSTMENT"
)

// Earning represents a single earning record for a crew member from an assignment.
type Earning struct {
	ID           uuid.UUID   `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	AssignmentID uuid.UUID   `json:"assignment_id" gorm:"type:uuid;not null;index"`
	CrewMemberID uuid.UUID   `json:"crew_member_id" gorm:"type:uuid;not null;index"`
	AmountCents  int64       `json:"amount_cents" gorm:"type:bigint;not null"`
	Currency     string      `json:"currency" gorm:"default:'KES';not null"`
	EarningType  EarningType `json:"earning_type" gorm:"not null"`
	Description  string      `json:"description,omitempty"`
	IsVerified   bool        `json:"is_verified" gorm:"default:false"`
	EarnedAt     time.Time   `json:"earned_at" gorm:"not null;index"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`

	// Relations
	Assignment Assignment `json:"-" gorm:"foreignKey:AssignmentID"`
	CrewMember CrewMember `json:"-" gorm:"foreignKey:CrewMemberID"`
}

func (Earning) TableName() string { return "earnings" }

// DailyEarningsSummary aggregates a crew member's daily earnings.
// Generated by nightly Asynq job, recalculable via admin endpoint.
type DailyEarningsSummary struct {
	ID                   uuid.UUID `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	CrewMemberID         uuid.UUID `json:"crew_member_id" gorm:"type:uuid;not null"`
	Date                 time.Time `json:"date" gorm:"type:date;not null"`
	TotalEarnedCents     int64     `json:"total_earned_cents" gorm:"type:bigint;default:0"`
	TotalDeductionsCents int64     `json:"total_deductions_cents" gorm:"type:bigint;default:0"`
	NetAmountCents       int64     `json:"net_amount_cents" gorm:"type:bigint;default:0"`
	Currency             string    `json:"currency" gorm:"default:'KES';not null"`
	AssignmentCount      int       `json:"assignment_count"`
	IsProcessed          bool      `json:"is_processed" gorm:"default:false"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

func (DailyEarningsSummary) TableName() string { return "daily_earnings_summaries" }
